### ISSUE TITLE
some issues about mmdet3.0

### ISSUE THREAD

**Issue by chunxt** [zht8506/UniHead#1]
Hi, in mmdetection3.0, the uniHead code has some problems, such as  @force_fp32(apply_to=('cls_scores', 'bbox_preds', 'centernesses')) def loss(). Because there is no force_fp32 in mmdetection3.0. How to solve it?

**Comment by zht8506** [comment]
UniHead does not involve modification of loss. You can use it freely in mmdetection3.0 with only a few modifications. For example, if you want to use Unihead in ATSS, you can refer to https://github.com/zht8506/UniHead/blob/5871d8ff0d32d230354245611c2079a9b206f0f0/mmdet/models/dense_heads/ATSSHead_Uni.py#L68C28-L122, and make modifications on https://github.com/open-mmlab/mmdetection/blob/fe3f809a0a514189baf889aa358c498d51ee36cd/mmdet/models/dense_heads/atss_head.py#L85-L127.

**Comment by zht8506** [comment]
You may need to reinstall mmdetection3.0, to make your modification effective. Or, you can make the train_shell files in the mmdetetion instead in mmdetection/tools. Refer to https://github.com/zht8506/UniHead/blob/main/dist_train_UniHead.sh. You also need to modify mmdetetion/models/dense_heads/__init__.py. Refer to  https://github.com/zht8506/UniHead/blob/main/mmdet/models/dense_heads/__init__.py.

**Comment by chunxt** [comment]
> You may need to reinstall mmdetection3.0, to make your modification effective. Or, you can make the train_shell files in the mmdetetion instead in mmdetection/tools. Refer to https://github.com/zht8506/UniHead/blob/main/dist_train_UniHead.sh. You also need to modify mmdetetion/models/dense_heads/**init**.py. Refer to https://github.com/zht8506/UniHead/blob/main/mmdet/models/dense_heads/__init__.py.

yes, I have done it. But, the question is there is no valid package, such as mmdet.core and mmcv.runner in atsshead_uni.py in mmdetection3.2.

**Comment by zht8506** [comment]
> > You may need to reinstall mmdetection3.0, to make your modification effective. Or, you can make the train_shell files in the mmdetetion instead in mmdetection/tools. Refer to https://github.com/zht8506/UniHead/blob/main/dist_train_UniHead.sh. You also need to modify mmdetetion/models/dense_heads/**init**.py. Refer to https://github.com/zht8506/UniHead/blob/main/mmdet/models/dense_heads/__init__.py.
> 
> yes, I have done it. But, the question is there is no valid package, such as mmdet.core and mmcv.runner in atsshead_uni.py in mmdetection3.2.

you just need to modify '_init_layers' function in mmdetection/mmdet/models/dense_heads/atss_head.py, and other code should be same as mmdetection3.2. Please don't copy all code from  ATSSHead_Uni.py

**Comment by chunxt** [comment]
> > > You may need to reinstall mmdetection3.0, to make your modification effective. Or, you can make the train_shell files in the mmdetetion instead in mmdetection/tools. Refer to https://github.com/zht8506/UniHead/blob/main/dist_train_UniHead.sh. You also need to modify mmdetetion/models/dense_heads/**init**.py. Refer to https://github.com/zht8506/UniHead/blob/main/mmdet/models/dense_heads/__init__.py.
> > 
> > 
> > yes, I have done it. But, the question is there is no valid package, such as mmdet.core and mmcv.runner in atsshead_uni.py in mmdetection3.2.
> 
> you just need to modify '_init_layers' function in mmdetection/mmdet/models/dense_heads/atss_head.py, and other code should be same as mmdetection3.2. Please don't copy all code from ATSSHead_Uni.py

_init_layers? why? And what's the meaning of "Please don't copy all code from ATSSHead_Uni.py"? I have no idea. Now, I want to retest the atsshead_Uni in mmdetection3.x. In my env, the "from mmdet.core import .." is none.

**Comment by zht8506** [comment]
> > > > You may need to reinstall mmdetection3.0, to make your modification effective. Or, you can make the train_shell files in the mmdetetion instead in mmdetection/tools. Refer to https://github.com/zht8506/UniHead/blob/main/dist_train_UniHead.sh. You also need to modify mmdetetion/models/dense_heads/**init**.py. Refer to https://github.com/zht8506/UniHead/blob/main/mmdet/models/dense_heads/__init__.py.
> > > 
> > > 
> > > yes, I have done it. But, the question is there is no valid package, such as mmdet.core and mmcv.runner in atsshead_uni.py in mmdetection3.2.
> > 
> > 
> > you just need to modify '_init_layers' function in mmdetection/mmdet/models/dense_heads/atss_head.py, and other code should be same as mmdetection3.2. Please don't copy all code from ATSSHead_Uni.py
> 
> _init_layers? why? And what's the meaning of "Please don't copy all code from ATSSHead_Uni.py"? I have no idea. Now, I want to retest the atsshead_Uni in mmdetection3.x. In my env, the "from mmdet.core import .." is none.

because ATSSHead_Uni.py just modify _init_layers function in atss.py, and the other code are same as atss.py. we replace the parallel head with unihead, and the others are same as the official code.
another way you can try is that create a new env in conda, and install mmdet==2.25.1, mmcv-full=1.7.0.

**Comment by chunxt** [comment]
> > > > > You may need to reinstall mmdetection3.0, to make your modification effective. Or, you can make the train_shell files in the mmdetetion instead in mmdetection/tools. Refer to https://github.com/zht8506/UniHead/blob/main/dist_train_UniHead.sh. You also need to modify mmdetetion/models/dense_heads/**init**.py. Refer to https://github.com/zht8506/UniHead/blob/main/mmdet/models/dense_heads/__init__.py.
> > > > 
> > > > 
> > > > yes, I have done it. But, the question is there is no valid package, such as mmdet.core and mmcv.runner in atsshead_uni.py in mmdetection3.2.
> > > 
> > > 
> > > you just need to modify '_init_layers' function in mmdetection/mmdet/models/dense_heads/atss_head.py, and other code should be same as mmdetection3.2. Please don't copy all code from ATSSHead_Uni.py
> > 
> > 
> > _init_layers? why? And what's the meaning of "Please don't copy all code from ATSSHead_Uni.py"? I have no idea. Now, I want to retest the atsshead_Uni in mmdetection3.x. In my env, the "from mmdet.core import .." is none.
> 
> because ATSSHead_Uni.py just modify _init_layers function in atss.py, and the other code are same as atss.py. we replace the parallel head with unihead, and the others are same as the official code. another way you can try is that create a new env in conda, and install mmdet==2.25.1, mmcv-full=1.7.0.

Thank you very much. I have solved it.
