### ISSUE TITLE
About GFlOPs

### ISSUE THREAD

**Issue by duzw9311** [zht8506/UniHead#3]
Thank you for your work. May I ask why the FLOPs obtained by get_flops.py in the MMdetection framework are smaller than those given in the paper?

**Comment by zht8506** [comment]
Thank you for your attention. Because the get_flops.py doesn't include the calculation amount of Transformer block, i.e, the FLOPs of (Q * K) *V. So, i suggest to calculate the FLOPs of this part by hand.

**Comment by duzw9311** [comment]
OK, thank you for your reply.
